---
title: "Day4"
author: "Johannes Friedrich"
date: "12/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
```

## Puzzle 1

```{r read_file}
## read in the file line by line
input <- scan("input.txt", what="", sep="\n",blank.lines.skip=FALSE) %>% 
  as.data.frame() %>% 
  rename("data" =".") %>% 
  mutate(id = cumsum(. == '')) %>% ## create IDs
  filter(data != "") ## remove empty lines now
```

```{r}
# create data.frame 
# idea: read line by line, split by whitespace and then split by ":" to get key:value pairs

df <- NULL
for (line in 1:nrow(input)){
  
  temp <- unlist(str_split(input$data[line], " "))
  temp <- str_split(temp, ":") %>% 
    purrr::map_dfr(~as.data.frame(t(.x))) %>% 
    rename("key" = "V1",
           "value" = "V2") %>% 
    mutate(id = input$id[line])
  
  df <- df %>% 
    bind_rows(temp)

}
```

```{r}
valid <- c("byr","iyr", "eyr", "hgt", "hcl", "ecl", "pid")

 
df %>% 
  group_by(id) %>% 
  mutate(all_keys = all(valid %in% key)) %>%  ## check if the needed keys are available 
  filter(all_keys == TRUE) %>% 
  group_by(id) %>% 
  tally() %>% 
  nrow()

```

## Puzzle 2

```{r}

valid_eyecolor <- c("amb", "blu", "brn", "gry", "grn", "hzl", "oth")
valid_hcl <- c("0","1","2","3","4", "5","6", "7", "8", "9", "a", "b", "c", "d", "e", "f")

df <- df %>% 
  group_by(id) %>% 
  mutate(all_keys = all(valid %in% key)) %>%  ## check if the needed keys are available 
  filter(all_keys == TRUE) %>% 
  spread(key, value) %>% 
  group_by(id) %>% 
  mutate(byr = as.numeric(byr),
         cid = as.numeric(cid),
         eyr = as.numeric(eyr),
         iyr = as.numeric(iyr),
         pid = pid,
         unit_hgt = if_else(str_sub(hgt,-2) == "cm","cm", "in")) %>% 
  filter(byr <= 2002,
         byr >= 1920,
         iyr >= 2010, 
         iyr <= 2020,
         eyr >= 2020,
         eyr <= 2030,
         ecl %in% valid_eyecolor,
         nchar(pid) == 9,
         str_sub(hcl,1,1) =="#",
         nchar(str_sub(hcl,2,-1)) == 6
         #all(valid_hcl %in% str_split(str_sub(hcl,2,-1), ""))  
         )
df
```

